#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 15:37:53 2019

@author: lordxuzhiyu
"""

# -*- coding: utf-8 -*-

import requests
import json
import pandas as pd

df = pd.read_csv('/Users/lordxuzhiyu/Desktop/Penthouse_Listing_SS.csv')

df.reset_index(drop = True)
df = df.drop(['Unnamed: 0'],axis = 1)

def split_line(text):
    words = text.split(',')
    result = []
    for word in words:
        result.append(word)
    return result

head = {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
    'connection': 'keep-alive'        
}
count = 0

new = pd.DataFrame()

for index, row in df.iterrows():
    add = row['Address']
    listing = str(add).split(',')
    try:
        full = listing[0]
        l = full.split(' ')
        num = l[0]
        del(l[0])
        street = ' '.join(l)
        url = 'https://api.cityofnewyork.us/geoclient/v1/address.json?houseNumber=' + num + '&street=' + street + '&borough=manhattan&app_id=35348ee9&app_key=874bc0a8aaafe29bbe84abaeb78fd57d'
        r = requests.get(url, headers = head)
        rjson = r.json()
        rjson = json.dumps(rjson)
        json_dict = json.loads(rjson)
        try:
            count += 1
            #print(url)
            bins = json_dict['address']['buildingIdentificationNumber']
            new.loc[index, 'Address'] = add
            new.loc[index, 'Bin'] = bins
            new.loc[index, 'Street'] = street
            new.loc[index, 'Street Number'] = num
        except Exception as e2:
            print('e2:', e2)
            continue
    except Exception as e1:
        print('e1:', e1)
        continue
    
print(count)
new.to_csv('/Users/lordxuzhiyu/Desktop/new.csv')
